import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react';
import SearchAppBar from "@/components/Navbar/SearchAppBar";
import AuthProvider from "@/Providers/AuthProvider";
import { useRouter } from 'next/navigation';
import { useLocation } from "react-router-dom";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        {/* <SearchAppBar></SearchAppBar> */}
        <Navbar></Navbar>
        
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}

// import React, { useContext } from 'react';
// import dynamic from 'next/dynamic'; // Import dynamic from next/dynamic
// import SearchAppBar from '@/components/Navbar/SearchAppBar';
// import AuthProvider from '@/Providers/AuthProvider';
// import { AuthContext } from '@/Providers/AuthProvider';

// // Dynamic import of useRouter to ensure it's only used on the client side
// const useRouterClient = dynamic(() => import('next/router'), { ssr: false });

// export default function RootLayout({ children }) {
//   // Use useRouterClient instead of useRouter
//   const router = useRouterClient();
//   const { user } = useContext(AuthContext);

//   // useEffect(() => {
//     if (!user) {
//       router.push('/login');
//     }
//   // }, [user, router]);
 
//   return (
//     <html lang="en">
//       <body>
//         <AuthProvider>
//           <SearchAppBar />
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
